name: my_fitness_tracker
description: "A fitness trainings tracker."
publish_to: "none"

version: 0.0.2+2

environment:
  sdk: ^3.5.3

dependencies:
  animated_custom_dropdown: ^3.1.1
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  back_button_interceptor: ^8.0.0
  bloc: ^9.0.0
  bot_toast: ^4.1.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_file_store: ^1.2.3
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  expandable: ^5.0.1
  fl_chart: ^0.70.2
  fl_location: ^5.0.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_bloc: ^9.0.0
  flutter_foreground_task: ^8.17.0
  flutter_local_notifications: ^19.0.0-dev.7
  flutter_map: ^8.0.0
  flutter_map_cache: ^1.5.2
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^4.1.0
  flutter_tts: ^4.2.0
  get_it: ^8.0.0
  go_router: ^14.2.1
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  lottie: ^3.1.2
  lucide_icons_flutter: ^1.2.6
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pausable_timer: ^3.1.0+3
  permission_handler: ^11.3.1
  searchfield: ^1.2.4
  share_plus: ^10.1.4
  sqlite3_flutter_libs: ^0.5.30
  sqlite_async: ^0.11.4
  timezone: ^0.10.0
  toggle_switch: ^2.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

  assets:
    - assets/sounds/
    - assets/lottie/
    - assets/translations/
