name: my_fitness_tracker
description: "A fitness trainings tracker."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  animated_custom_dropdown: ^3.1.1
  easy_localization: ^3.0.7
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  go_router: ^14.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2771.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  bloc: ^8.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  top_snackbar_flutter: ^3.1.0
  searchfield: ^1.1.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600

  assets:
    - lib/assets/lottie/
    - lib/assets/svg/
    - lib/assets/translations/
