name: my_fitness_tracker
description: "A fitness trainings tracker."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_custom_dropdown: ^3.1.1
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  back_button_interceptor: ^8.0.0
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.2.0
  get_it: ^8.0.0
  go_router: ^14.2.1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  material_symbols_icons: ^4.2771.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pausable_timer: ^3.1.0+3
  location: ^7.0.1
  searchfield: 1.1.8
  shared_preferences: ^2.3.5
  sqflite: ^2.3.3+1
  top_snackbar_flutter: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

  assets:
    - assets/sounds/
    - assets/lottie/
    - assets/translations/
