// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/exercise_management/models/exercise.dart';
import 'features/training_history/data/models/training_version.dart';
import 'features/training_management/models/multiset.dart';
import 'features/training_management/models/training.dart';
import 'features/training_management/models/training_exercise.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7837023745425483267),
      name: 'Multiset',
      lastPropertyId: const obx_int.IdUid(11, 7425754225602225605),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8719446480133154916),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6013580209830941836),
            name: 'sets',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2508266651475172113),
            name: 'setRest',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1435541522072950637),
            name: 'multisetRest',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1717837802590117520),
            name: 'specialInstructions',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6039037355741241067),
            name: 'objectives',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8381868419772571920),
            name: 'position',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 201493524754498310),
            name: 'key',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7425754225602225605),
            name: 'linkedTrainingId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 8212219717969508965),
            name: 'trainingExercises',
            targetId: const obx_int.IdUid(3, 4756948127312470496))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2932161035028909040),
      name: 'Training',
      lastPropertyId: const obx_int.IdUid(7, 3629004880923664589),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3515765141364894896),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3135303093556622218),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5016644797159749358),
            name: 'objectives',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6786941717840464610),
            name: 'dbType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3629004880923664589),
            name: 'dbTrainingDays',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 4935659058856285213),
            name: 'trainingExercises',
            targetId: const obx_int.IdUid(3, 4756948127312470496)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 3289185353329412385),
            name: 'multisets',
            targetId: const obx_int.IdUid(1, 7837023745425483267)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 2557248783965981805),
            name: 'trainingVersions',
            targetId: const obx_int.IdUid(5, 790968269672532113))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4756948127312470496),
      name: 'TrainingExercise',
      lastPropertyId: const obx_int.IdUid(28, 6290711620444277774),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6108871729213740517),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7429479038024413978),
            name: 'exerciseId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 553719026357103129),
            relationTarget: 'Exercise'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7569012901362455937),
            name: 'specialInstructions',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8107865731497299671),
            name: 'objectives',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5459245783809742483),
            name: 'targetDistance',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4621418631557638427),
            name: 'targetDuration',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1852368107492337616),
            name: 'isTargetPaceSelected',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8806688819027779267),
            name: 'targetPace',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 128248959963900822),
            name: 'sets',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1223404940800654621),
            name: 'isSetsInReps',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2924402670291120286),
            name: 'minReps',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 1980150629980597560),
            name: 'maxReps',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 4906135197889964248),
            name: 'duration',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 7894728641131780750),
            name: 'setRest',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 979885308642330532),
            name: 'exerciseRest',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 5357601499003534908),
            name: 'isAutoStart',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4603778332535153773),
            name: 'position',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 597337282396317998),
            name: 'intensity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 702072385444039418),
            name: 'key',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 3729112720790051269),
            name: 'dbType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 4843306632898592410),
            name: 'dbRunType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 8546346913216974507),
            name: 'linkedExerciseId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 505361365510310397),
            name: 'linkedTrainingId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 6290711620444277774),
            name: 'linkedMultisetId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 1371781158635934480),
      name: 'Exercise',
      lastPropertyId: const obx_int.IdUid(6, 5199546075756722168),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5819755668094325734),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 271087027588398860),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 693625742645067785),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2216787406317418660),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7319180526493872213),
            name: 'dbType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5199546075756722168),
            name: 'dbMuscleGroups',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 790968269672532113),
      name: 'TrainingVersion',
      lastPropertyId: const obx_int.IdUid(6, 6819686565950909175),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2848876468079718365),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2732075275205302973),
            name: 'trainingId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 9020215719984396004),
            relationTarget: 'Training'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5572835714115388081),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8588810811449880299),
            name: 'dbType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2015978338742949354),
            name: 'objectives',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6819686565950909175),
            name: 'dbTrainingDays',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(5, 2220873685979633358),
            name: 'trainingExercises',
            targetId: const obx_int.IdUid(3, 4756948127312470496)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(6, 525592784003240916),
            name: 'multisets',
            targetId: const obx_int.IdUid(1, 7837023745425483267))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 790968269672532113),
      lastIndexId: const obx_int.IdUid(9, 553719026357103129),
      lastRelationId: const obx_int.IdUid(6, 525592784003240916),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [
        1997644619502088310,
        262618515223658650,
        1984868986684376430,
        9077253555612493925,
        5680325267104003293,
        3749658864148140912,
        746187908374442006
      ],
      retiredPropertyUids: const [
        7117997750659844272,
        7208038991482613170,
        8957684371679850546,
        2995742759851243026,
        5528278541389928687,
        7592199348303741118,
        1581587549710862424,
        4041142347862379862
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Multiset: obx_int.EntityDefinition<Multiset>(
        model: _entities[0],
        toOneRelations: (Multiset object) => [],
        toManyRelations: (Multiset object) => {
              obx_int.RelInfo<Multiset>.toMany(1, object.id):
                  object.trainingExercises
            },
        getId: (Multiset object) => object.id,
        setId: (Multiset object, int id) {
          object.id = id;
        },
        objectToFB: (Multiset object, fb.Builder fbb) {
          final specialInstructionsOffset = object.specialInstructions == null
              ? null
              : fbb.writeString(object.specialInstructions!);
          final objectivesOffset = object.objectives == null
              ? null
              : fbb.writeString(object.objectives!);
          final keyOffset =
              object.key == null ? null : fbb.writeString(object.key!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.sets);
          fbb.addInt64(2, object.setRest);
          fbb.addInt64(3, object.multisetRest);
          fbb.addOffset(4, specialInstructionsOffset);
          fbb.addOffset(5, objectivesOffset);
          fbb.addInt64(6, object.position);
          fbb.addOffset(7, keyOffset);
          fbb.addInt64(10, object.linkedTrainingId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final linkedTrainingIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24);
          final setsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final setRestParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final multisetRestParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final positionParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final keyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final object = Multiset(
              id: idParam,
              linkedTrainingId: linkedTrainingIdParam,
              sets: setsParam,
              setRest: setRestParam,
              multisetRest: multisetRestParam,
              position: positionParam,
              key: keyParam)
            ..specialInstructions =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 12)
            ..objectives = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14);
          obx_int.InternalToManyAccess.setRelInfo<Multiset>(
              object.trainingExercises,
              store,
              obx_int.RelInfo<Multiset>.toMany(1, object.id));
          return object;
        }),
    Training: obx_int.EntityDefinition<Training>(
        model: _entities[1],
        toOneRelations: (Training object) => [],
        toManyRelations: (Training object) => {
              obx_int.RelInfo<Training>.toMany(2, object.id):
                  object.trainingExercises,
              obx_int.RelInfo<Training>.toMany(3, object.id): object.multisets,
              obx_int.RelInfo<Training>.toMany(4, object.id):
                  object.trainingVersions
            },
        getId: (Training object) => object.id,
        setId: (Training object, int id) {
          object.id = id;
        },
        objectToFB: (Training object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final objectivesOffset = object.objectives == null
              ? null
              : fbb.writeString(object.objectives!);
          final dbTrainingDaysOffset = object.dbTrainingDays == null
              ? null
              : fbb.writeString(object.dbTrainingDays!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(3, objectivesOffset);
          fbb.addInt64(5, object.dbType);
          fbb.addOffset(6, dbTrainingDaysOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Training(nameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..objectives = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..dbType =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14)
            ..dbTrainingDays = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16);
          obx_int.InternalToManyAccess.setRelInfo<Training>(
              object.trainingExercises,
              store,
              obx_int.RelInfo<Training>.toMany(2, object.id));
          obx_int.InternalToManyAccess.setRelInfo<Training>(object.multisets,
              store, obx_int.RelInfo<Training>.toMany(3, object.id));
          obx_int.InternalToManyAccess.setRelInfo<Training>(
              object.trainingVersions,
              store,
              obx_int.RelInfo<Training>.toMany(4, object.id));
          return object;
        }),
    TrainingExercise: obx_int.EntityDefinition<TrainingExercise>(
        model: _entities[2],
        toOneRelations: (TrainingExercise object) => [object.exercise],
        toManyRelations: (TrainingExercise object) => {},
        getId: (TrainingExercise object) => object.id,
        setId: (TrainingExercise object, int id) {
          object.id = id;
        },
        objectToFB: (TrainingExercise object, fb.Builder fbb) {
          final specialInstructionsOffset = object.specialInstructions == null
              ? null
              : fbb.writeString(object.specialInstructions!);
          final objectivesOffset = object.objectives == null
              ? null
              : fbb.writeString(object.objectives!);
          final keyOffset =
              object.key == null ? null : fbb.writeString(object.key!);
          fbb.startTable(29);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.exercise.targetId);
          fbb.addOffset(3, specialInstructionsOffset);
          fbb.addOffset(4, objectivesOffset);
          fbb.addInt64(6, object.targetDistance);
          fbb.addInt64(7, object.targetDuration);
          fbb.addBool(8, object.isTargetPaceSelected);
          fbb.addInt64(9, object.targetPace);
          fbb.addInt64(10, object.sets);
          fbb.addBool(11, object.isSetsInReps);
          fbb.addInt64(12, object.minReps);
          fbb.addInt64(13, object.maxReps);
          fbb.addInt64(14, object.duration);
          fbb.addInt64(15, object.setRest);
          fbb.addInt64(16, object.exerciseRest);
          fbb.addBool(17, object.isAutoStart);
          fbb.addInt64(18, object.position);
          fbb.addInt64(19, object.intensity);
          fbb.addOffset(20, keyOffset);
          fbb.addInt64(21, object.dbType);
          fbb.addInt64(22, object.dbRunType);
          fbb.addInt64(25, object.linkedExerciseId);
          fbb.addInt64(26, object.linkedTrainingId);
          fbb.addInt64(27, object.linkedMultisetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final setsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final isSetsInRepsParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final isAutoStartParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 38, false);
          final intensityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0);
          final object = TrainingExercise(
              sets: setsParam,
              isSetsInReps: isSetsInRepsParam,
              isAutoStart: isAutoStartParam,
              intensity: intensityParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..specialInstructions =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 10)
            ..objectives = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..targetDistance =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..targetDuration =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18)
            ..isTargetPaceSelected =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 20)
            ..targetPace =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22)
            ..minReps =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28)
            ..maxReps =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 30)
            ..duration =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 32)
            ..setRest =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34)
            ..exerciseRest =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 36)
            ..position =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 40)
            ..key = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 44)
            ..dbType =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 46)
            ..dbRunType =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 48)
            ..linkedExerciseId =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 54)
            ..linkedTrainingId =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 56)
            ..linkedMultisetId = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 58);
          object.exercise.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.exercise.attach(store);
          return object;
        }),
    Exercise: obx_int.EntityDefinition<Exercise>(
        model: _entities[3],
        toOneRelations: (Exercise object) => [],
        toManyRelations: (Exercise object) => {},
        getId: (Exercise object) => object.id,
        setId: (Exercise object, int id) {
          object.id = id;
        },
        objectToFB: (Exercise object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final dbMuscleGroupsOffset = object.dbMuscleGroups == null
              ? null
              : fbb.writeString(object.dbMuscleGroups!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, imagePathOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.dbType);
          fbb.addOffset(5, dbMuscleGroupsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Exercise(nameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..imagePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..dbType =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12)
            ..dbMuscleGroups = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14);

          return object;
        }),
    TrainingVersion: obx_int.EntityDefinition<TrainingVersion>(
        model: _entities[4],
        toOneRelations: (TrainingVersion object) => [object.training],
        toManyRelations: (TrainingVersion object) => {
              obx_int.RelInfo<TrainingVersion>.toMany(5, object.id):
                  object.trainingExercises,
              obx_int.RelInfo<TrainingVersion>.toMany(6, object.id):
                  object.multisets
            },
        getId: (TrainingVersion object) => object.id,
        setId: (TrainingVersion object, int id) {
          object.id = id;
        },
        objectToFB: (TrainingVersion object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final objectivesOffset = object.objectives == null
              ? null
              : fbb.writeString(object.objectives!);
          final dbTrainingDaysOffset = object.dbTrainingDays == null
              ? null
              : fbb.writeString(object.dbTrainingDays!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.training.targetId);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.dbType);
          fbb.addOffset(4, objectivesOffset);
          fbb.addOffset(5, dbTrainingDaysOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final dbTypeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final objectivesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final dbTrainingDaysParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final object = TrainingVersion(
              nameParam, dbTypeParam, objectivesParam, dbTrainingDaysParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.training.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.training.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<TrainingVersion>(
              object.trainingExercises,
              store,
              obx_int.RelInfo<TrainingVersion>.toMany(5, object.id));
          obx_int.InternalToManyAccess.setRelInfo<TrainingVersion>(
              object.multisets,
              store,
              obx_int.RelInfo<TrainingVersion>.toMany(6, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Multiset] entity fields to define ObjectBox queries.
class Multiset_ {
  /// See [Multiset.id].
  static final id =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[0]);

  /// See [Multiset.sets].
  static final sets =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[1]);

  /// See [Multiset.setRest].
  static final setRest =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[2]);

  /// See [Multiset.multisetRest].
  static final multisetRest =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[3]);

  /// See [Multiset.specialInstructions].
  static final specialInstructions =
      obx.QueryStringProperty<Multiset>(_entities[0].properties[4]);

  /// See [Multiset.objectives].
  static final objectives =
      obx.QueryStringProperty<Multiset>(_entities[0].properties[5]);

  /// See [Multiset.position].
  static final position =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[6]);

  /// See [Multiset.key].
  static final key =
      obx.QueryStringProperty<Multiset>(_entities[0].properties[7]);

  /// See [Multiset.linkedTrainingId].
  static final linkedTrainingId =
      obx.QueryIntegerProperty<Multiset>(_entities[0].properties[8]);

  /// see [Multiset.trainingExercises]
  static final trainingExercises =
      obx.QueryRelationToMany<Multiset, TrainingExercise>(
          _entities[0].relations[0]);
}

/// [Training] entity fields to define ObjectBox queries.
class Training_ {
  /// See [Training.id].
  static final id =
      obx.QueryIntegerProperty<Training>(_entities[1].properties[0]);

  /// See [Training.name].
  static final name =
      obx.QueryStringProperty<Training>(_entities[1].properties[1]);

  /// See [Training.objectives].
  static final objectives =
      obx.QueryStringProperty<Training>(_entities[1].properties[2]);

  /// See [Training.dbType].
  static final dbType =
      obx.QueryIntegerProperty<Training>(_entities[1].properties[3]);

  /// See [Training.dbTrainingDays].
  static final dbTrainingDays =
      obx.QueryStringProperty<Training>(_entities[1].properties[4]);

  /// see [Training.trainingExercises]
  static final trainingExercises =
      obx.QueryRelationToMany<Training, TrainingExercise>(
          _entities[1].relations[0]);

  /// see [Training.multisets]
  static final multisets =
      obx.QueryRelationToMany<Training, Multiset>(_entities[1].relations[1]);

  /// see [Training.trainingVersions]
  static final trainingVersions =
      obx.QueryRelationToMany<Training, TrainingVersion>(
          _entities[1].relations[2]);
}

/// [TrainingExercise] entity fields to define ObjectBox queries.
class TrainingExercise_ {
  /// See [TrainingExercise.id].
  static final id =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[0]);

  /// See [TrainingExercise.exercise].
  static final exercise = obx.QueryRelationToOne<TrainingExercise, Exercise>(
      _entities[2].properties[1]);

  /// See [TrainingExercise.specialInstructions].
  static final specialInstructions =
      obx.QueryStringProperty<TrainingExercise>(_entities[2].properties[2]);

  /// See [TrainingExercise.objectives].
  static final objectives =
      obx.QueryStringProperty<TrainingExercise>(_entities[2].properties[3]);

  /// See [TrainingExercise.targetDistance].
  static final targetDistance =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[4]);

  /// See [TrainingExercise.targetDuration].
  static final targetDuration =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[5]);

  /// See [TrainingExercise.isTargetPaceSelected].
  static final isTargetPaceSelected =
      obx.QueryBooleanProperty<TrainingExercise>(_entities[2].properties[6]);

  /// See [TrainingExercise.targetPace].
  static final targetPace =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[7]);

  /// See [TrainingExercise.sets].
  static final sets =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[8]);

  /// See [TrainingExercise.isSetsInReps].
  static final isSetsInReps =
      obx.QueryBooleanProperty<TrainingExercise>(_entities[2].properties[9]);

  /// See [TrainingExercise.minReps].
  static final minReps =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[10]);

  /// See [TrainingExercise.maxReps].
  static final maxReps =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[11]);

  /// See [TrainingExercise.duration].
  static final duration =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[12]);

  /// See [TrainingExercise.setRest].
  static final setRest =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[13]);

  /// See [TrainingExercise.exerciseRest].
  static final exerciseRest =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[14]);

  /// See [TrainingExercise.isAutoStart].
  static final isAutoStart =
      obx.QueryBooleanProperty<TrainingExercise>(_entities[2].properties[15]);

  /// See [TrainingExercise.position].
  static final position =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[16]);

  /// See [TrainingExercise.intensity].
  static final intensity =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[17]);

  /// See [TrainingExercise.key].
  static final key =
      obx.QueryStringProperty<TrainingExercise>(_entities[2].properties[18]);

  /// See [TrainingExercise.dbType].
  static final dbType =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[19]);

  /// See [TrainingExercise.dbRunType].
  static final dbRunType =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[20]);

  /// See [TrainingExercise.linkedExerciseId].
  static final linkedExerciseId =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[21]);

  /// See [TrainingExercise.linkedTrainingId].
  static final linkedTrainingId =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[22]);

  /// See [TrainingExercise.linkedMultisetId].
  static final linkedMultisetId =
      obx.QueryIntegerProperty<TrainingExercise>(_entities[2].properties[23]);
}

/// [Exercise] entity fields to define ObjectBox queries.
class Exercise_ {
  /// See [Exercise.id].
  static final id =
      obx.QueryIntegerProperty<Exercise>(_entities[3].properties[0]);

  /// See [Exercise.name].
  static final name =
      obx.QueryStringProperty<Exercise>(_entities[3].properties[1]);

  /// See [Exercise.imagePath].
  static final imagePath =
      obx.QueryStringProperty<Exercise>(_entities[3].properties[2]);

  /// See [Exercise.description].
  static final description =
      obx.QueryStringProperty<Exercise>(_entities[3].properties[3]);

  /// See [Exercise.dbType].
  static final dbType =
      obx.QueryIntegerProperty<Exercise>(_entities[3].properties[4]);

  /// See [Exercise.dbMuscleGroups].
  static final dbMuscleGroups =
      obx.QueryStringProperty<Exercise>(_entities[3].properties[5]);
}

/// [TrainingVersion] entity fields to define ObjectBox queries.
class TrainingVersion_ {
  /// See [TrainingVersion.id].
  static final id =
      obx.QueryIntegerProperty<TrainingVersion>(_entities[4].properties[0]);

  /// See [TrainingVersion.training].
  static final training = obx.QueryRelationToOne<TrainingVersion, Training>(
      _entities[4].properties[1]);

  /// See [TrainingVersion.name].
  static final name =
      obx.QueryStringProperty<TrainingVersion>(_entities[4].properties[2]);

  /// See [TrainingVersion.dbType].
  static final dbType =
      obx.QueryIntegerProperty<TrainingVersion>(_entities[4].properties[3]);

  /// See [TrainingVersion.objectives].
  static final objectives =
      obx.QueryStringProperty<TrainingVersion>(_entities[4].properties[4]);

  /// See [TrainingVersion.dbTrainingDays].
  static final dbTrainingDays =
      obx.QueryStringProperty<TrainingVersion>(_entities[4].properties[5]);

  /// see [TrainingVersion.trainingExercises]
  static final trainingExercises =
      obx.QueryRelationToMany<TrainingVersion, TrainingExercise>(
          _entities[4].relations[0]);

  /// see [TrainingVersion.multisets]
  static final multisets = obx.QueryRelationToMany<TrainingVersion, Multiset>(
      _entities[4].relations[1]);
}
